export interface Question {
  id: string;
  text: string;
  category: string;
  type: 'select' | 'number' | 'text' | 'boolean';
  options?: string[];
}

export const ASSESSMENT_QUESTIONS: Question[] = [
  // FITNESS & ENERGY (17 Questions)
  { id: 'q_fit_01', text: 'How many days per week do you exercise?', category: 'Fitness & Energy', type: 'number' },
  { id: 'q_fit_02', text: 'What type of exercise do you currently do?', category: 'Fitness & Energy', type: 'text' },
  { id: 'q_fit_03', text: 'How would you rate your physical fitness (1–10)?', category: 'Fitness & Energy', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_fit_04', text: 'Do you feel tired during the day?', category: 'Fitness & Energy', type: 'boolean' },
  { id: 'q_fit_05', text: 'How many hours do you sleep daily?', category: 'Fitness & Energy', type: 'number' },
  { id: 'q_fit_06', text: 'Do you wake up feeling fresh?', category: 'Fitness & Energy', type: 'boolean' },
  { id: 'q_fit_07', text: 'How consistent is your sleep schedule?', category: 'Fitness & Energy', type: 'select', options: ['Very consistent', 'Somewhat consistent', 'Inconsistent'] },
  { id: 'q_fit_08', text: 'How often do you eat junk food?', category: 'Fitness & Energy', type: 'select', options: ['Daily', '2-3 times/week', 'Weekly', 'Monthly', 'Never'] },
  { id: 'q_fit_09', text: 'Do you follow any diet plan?', category: 'Fitness & Energy', type: 'boolean' },
  { id: 'q_fit_10', text: 'How much water do you drink daily?', category: 'Fitness & Energy', type: 'number' },
  { id: 'q_fit_11', text: 'Do you have any health issues?', category: 'Fitness & Energy', type: 'boolean' },
  { id: 'q_fit_12', text: 'How often do you feel low energy?', category: 'Fitness & Energy', type: 'select', options: ['Daily', 'Weekly', 'Rarely'] },
  { id: 'q_fit_13', text: 'Do you track your fitness (steps, calories)?', category: 'Fitness & Energy', type: 'boolean' },
  { id: 'q_fit_14', text: 'How motivated are you to work out?', category: 'Fitness & Energy', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_fit_15', text: 'What stops you from exercising regularly?', category: 'Fitness & Energy', type: 'text' },
  { id: 'q_fit_16', text: 'Do you spend long hours sitting?', category: 'Fitness & Energy', type: 'boolean' },
  { id: 'q_fit_17', text: 'What is your primary fitness goal?', category: 'Fitness & Energy', type: 'text' },

  // DISCIPLINE & HABITS (17 Questions)
  { id: 'q_disc_01', text: 'Do you follow a daily routine?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_02', text: 'How often do you complete planned tasks?', category: 'Discipline & Habits', type: 'select', options: ['Always', 'Usually', 'Sometimes', 'Rarely'] },
  { id: 'q_disc_03', text: 'Do you procrastinate?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_04', text: 'What time do you wake up daily?', category: 'Discipline & Habits', type: 'text' },
  { id: 'q_disc_05', text: 'Do you use a to-do list?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_06', text: 'How many habits are you currently tracking?', category: 'Discipline & Habits', type: 'number' },
  { id: 'q_disc_07', text: 'Do you get distracted easily?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_08', text: 'How many hours do you waste daily?', category: 'Discipline & Habits', type: 'number' },
  { id: 'q_disc_09', text: 'What are your biggest distractions?', category: 'Discipline & Habits', type: 'text' },
  { id: 'q_disc_10', text: 'Do you stick to commitments?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_11', text: 'How often do you break habits?', category: 'Discipline & Habits', type: 'select', options: ['Daily', 'Weekly', 'Rarely'] },
  { id: 'q_disc_12', text: 'Do you review your day?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_13', text: 'How consistent are you (1–10)?', category: 'Discipline & Habits', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_disc_14', text: 'Do you plan your next day?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_15', text: 'What habit do you struggle with most?', category: 'Discipline & Habits', type: 'text' },
  { id: 'q_disc_16', text: 'Do you reward yourself for discipline?', category: 'Discipline & Habits', type: 'boolean' },
  { id: 'q_disc_17', text: 'What time do you sleep daily?', category: 'Discipline & Habits', type: 'text' },

  // MONEY & WEALTH (17 Questions)
  { id: 'q_wealth_01', text: 'What is your current monthly income?', category: 'Money & Wealth', type: 'number' },
  { id: 'q_wealth_02', text: 'Do you have multiple income sources?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_03', text: 'How much do you save monthly?', category: 'Money & Wealth', type: 'number' },
  { id: 'q_wealth_04', text: 'Do you track your expenses?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_05', text: 'Do you invest money?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_06', text: 'What is your total savings?', category: 'Money & Wealth', type: 'number' },
  { id: 'q_wealth_07', text: 'Do you have any debt?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_08', text: 'What is your financial goal (1 year)?', category: 'Money & Wealth', type: 'text' },
  { id: 'q_wealth_09', text: 'How confident are you about money management?', category: 'Money & Wealth', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_wealth_10', text: 'Do you have emergency funds?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_11', text: 'How often do you learn about finance?', category: 'Money & Wealth', type: 'select', options: ['Daily', 'Weekly', 'Monthly', 'Rarely'] },
  { id: 'q_wealth_12', text: 'Do you rely only on salary?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_13', text: 'What skill are you building to earn more?', category: 'Money & Wealth', type: 'text' },
  { id: 'q_wealth_14', text: 'How much risk can you take financially?', category: 'Money & Wealth', type: 'select', options: ['High', 'Medium', 'Low'] },
  { id: 'q_wealth_15', text: 'What is your biggest money problem?', category: 'Money & Wealth', type: 'text' },
  { id: 'q_wealth_16', text: 'Do you follow a budget?', category: 'Money & Wealth', type: 'boolean' },
  { id: 'q_wealth_17', text: 'What motivates you to earn more?', category: 'Money & Wealth', type: 'text' },

  // LEARNING & SKILLS (17 Questions)
  { id: 'q_learn_01', text: 'How many hours do you learn daily?', category: 'Learning & Skills', type: 'number' },
  { id: 'q_learn_02', text: 'What skill are you currently learning?', category: 'Learning & Skills', type: 'text' },
  { id: 'q_learn_03', text: 'Do you follow structured learning?', category: 'Learning & Skills', type: 'boolean' },
  { id: 'q_learn_04', text: 'How consistent are you in learning?', category: 'Learning & Skills', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_learn_05', text: 'Do you take notes?', category: 'Learning & Skills', type: 'boolean' },
  { id: 'q_learn_06', text: 'Do you apply what you learn?', category: 'Learning & Skills', type: 'boolean' },
  { id: 'q_learn_07', text: 'What is your main career goal?', category: 'Learning & Skills', type: 'text' },
  { id: 'q_learn_08', text: 'Do you learn from books or videos?', category: 'Learning & Skills', type: 'select', options: ['Books', 'Videos', 'Both', 'Courses'] },
  { id: 'q_learn_09', text: 'How quickly do you implement knowledge?', category: 'Learning & Skills', type: 'select', options: ['Immediately', 'Within a week', 'Within a month', 'Rarely'] },
  { id: 'q_learn_10', text: 'Do you track learning progress?', category: 'Learning & Skills', type: 'boolean' },
  { id: 'q_learn_11', text: 'What stops you from learning regularly?', category: 'Learning & Skills', type: 'text' },
  { id: 'q_learn_12', text: 'Do you invest in courses?', category: 'Learning & Skills', type: 'boolean' },
  { id: 'q_learn_13', text: 'What high-income skill are you building?', category: 'Learning & Skills', type: 'text' },
  { id: 'q_learn_14', text: 'Do you have a mentor?', category: 'Learning & Skills', type: 'boolean' },
  { id: 'q_learn_15', text: 'How confident are you in your skills?', category: 'Learning & Skills', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_learn_16', text: 'What skill can earn you money in 6 months?', category: 'Learning & Skills', type: 'text' },
  { id: 'q_learn_17', text: 'Do you revise what you learn?', category: 'Learning & Skills', type: 'boolean' },

  // NETWORK & RELATIONSHIPS (16 Questions)
  { id: 'q_net_01', text: 'How strong is your professional network?', category: 'Network & Relationships', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_net_02', text: 'Do you actively meet new people?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_03', text: 'How often do you attend events?', category: 'Network & Relationships', type: 'select', options: ['Weekly', 'Monthly', 'Yearly', 'Never'] },
  { id: 'q_net_04', text: 'Do you maintain relationships regularly?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_05', text: 'Do you have mentors or guides?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_06', text: 'How supportive is your circle?', category: 'Network & Relationships', type: 'select', options: ['Very supportive', 'Somewhat supportive', 'Neutral', 'Toxic'] },
  { id: 'q_net_07', text: 'Do you connect with successful people?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_08', text: 'How often do you reach out to contacts?', category: 'Network & Relationships', type: 'select', options: ['Daily', 'Weekly', 'Monthly'] },
  { id: 'q_net_09', text: 'Do you help others grow?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_10', text: 'How good are your communication skills?', category: 'Network & Relationships', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_net_11', text: 'Do you avoid social interactions?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_12', text: 'How confident are you in conversations?', category: 'Network & Relationships', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_net_13', text: 'Do you use LinkedIn actively?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_14', text: 'How many meaningful connections do you have?', category: 'Network & Relationships', type: 'number' },
  { id: 'q_net_15', text: 'Do you collaborate with others?', category: 'Network & Relationships', type: 'boolean' },
  { id: 'q_net_16', text: 'What is your biggest relationship challenge?', category: 'Network & Relationships', type: 'text' },

  // MINDSET & FOCUS (17 Questions)
  { id: 'q_mind_01', text: 'How often do you feel stressed?', category: 'Mindset & Focus', type: 'select', options: ['Always', 'Often', 'Sometimes', 'Rarely'] },
  { id: 'q_mind_02', text: 'Do you overthink?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_03', text: 'How focused are you during work?', category: 'Mindset & Focus', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_mind_04', text: 'Do you get distracted by phone/social media?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_05', text: 'How confident are you in yourself?', category: 'Mindset & Focus', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_mind_06', text: 'Do you believe you can achieve big goals?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_07', text: 'How do you handle failure?', category: 'Mindset & Focus', type: 'text' },
  { id: 'q_mind_08', text: 'Do you compare yourself with others?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_09', text: 'How often do you feel motivated?', category: 'Mindset & Focus', type: 'select', options: ['Always', 'Usually', 'Sometimes', 'Rarely'] },
  { id: 'q_mind_10', text: 'Do you practice meditation?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_11', text: 'How clear are your life goals?', category: 'Mindset & Focus', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_mind_12', text: 'Do you have a long-term vision?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_13', text: 'What fears hold you back?', category: 'Mindset & Focus', type: 'text' },
  { id: 'q_mind_14', text: 'Do you take action despite fear?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_15', text: 'How positive is your mindset (1–10)?', category: 'Mindset & Focus', type: 'select', options: ['1','2','3','4','5','6','7','8','9','10'] },
  { id: 'q_mind_16', text: 'Do you journal or reflect?', category: 'Mindset & Focus', type: 'boolean' },
  { id: 'q_mind_17', text: 'What is your biggest mental challenge?', category: 'Mindset & Focus', type: 'text' },

  // Final Questions
  { id: 'vision3Year', text: 'Describe exactly who you want to become in 3 years. What does your life look like?', category: '1% Vision', type: 'text' },
  { id: 'targetIncome', text: 'What is your target annual income (in USD) to achieve absolute freedom?', category: '1% Vision', type: 'number' },
  { id: 'dreamCareer', text: 'What is your dream career, business, or contribution to the world?', category: '1% Vision', type: 'text' },
  { id: 'fitnessGoal', text: 'What is your peak physical goal? (e.g., body fat %, specific strength stats)', category: '1% Vision', type: 'text' },
];
